[package]
name = "rubust"
version = "0.1.0"
edition = "2021"
authors = ["Brian Penguin<btenggren20@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
csv = "1.2"
